/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUnlockCallback,
  IUnlockCallbackInterface,
} from "../../../../../../@uniswap/v4-core/src/interfaces/callback/IUnlockCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "unlockCallback",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUnlockCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IUnlockCallbackInterface {
    return new Interface(_abi) as IUnlockCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUnlockCallback {
    return new Contract(address, _abi, runner) as unknown as IUnlockCallback;
  }
}
