/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface StateLibraryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_GROWTH_GLOBAL0_OFFSET"
      | "LIQUIDITY_OFFSET"
      | "POOLS_SLOT"
      | "POSITIONS_OFFSET"
      | "TICKS_OFFSET"
      | "TICK_BITMAP_OFFSET"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FEE_GROWTH_GLOBAL0_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDITY_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOLS_SLOT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POSITIONS_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKS_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICK_BITMAP_OFFSET",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_GROWTH_GLOBAL0_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDITY_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "POOLS_SLOT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "POSITIONS_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKS_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICK_BITMAP_OFFSET",
    data: BytesLike
  ): Result;
}

export interface StateLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): StateLibrary;
  waitForDeployment(): Promise<this>;

  interface: StateLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_GROWTH_GLOBAL0_OFFSET: TypedContractMethod<[], [bigint], "view">;

  LIQUIDITY_OFFSET: TypedContractMethod<[], [bigint], "view">;

  POOLS_SLOT: TypedContractMethod<[], [string], "view">;

  POSITIONS_OFFSET: TypedContractMethod<[], [bigint], "view">;

  TICKS_OFFSET: TypedContractMethod<[], [bigint], "view">;

  TICK_BITMAP_OFFSET: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_GROWTH_GLOBAL0_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDITY_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "POOLS_SLOT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "POSITIONS_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TICKS_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TICK_BITMAP_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
