/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface PredictiveCommitmentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PENALTY_RATE"
      | "PENALTY_THRESHOLD"
      | "TIER_1_REWARD"
      | "TIER_1_THRESHOLD"
      | "TIER_2_REWARD"
      | "TIER_2_THRESHOLD"
      | "TIER_3_REWARD"
      | "TIER_3_THRESHOLD"
      | "commitments"
      | "submitCommitment"
      | "verifyAndReward"
      | "zkVerifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CommitmentSubmitted" | "CommitmentVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PENALTY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_1_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_1_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_2_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_2_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_3_REWARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_3_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitCommitment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndReward",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zkVerifier",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PENALTY_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_1_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_1_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_2_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_2_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_3_REWARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_3_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zkVerifier", data: BytesLike): Result;
}

export namespace CommitmentSubmittedEvent {
  export type InputTuple = [
    commitmentId: BytesLike,
    rentalId: BytesLike,
    committer: AddressLike,
    predictedDuration: BigNumberish
  ];
  export type OutputTuple = [
    commitmentId: string,
    rentalId: string,
    committer: string,
    predictedDuration: bigint
  ];
  export interface OutputObject {
    commitmentId: string;
    rentalId: string;
    committer: string;
    predictedDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommitmentVerifiedEvent {
  export type InputTuple = [
    commitmentId: BytesLike,
    predictionError: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    commitmentId: string,
    predictionError: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    commitmentId: string;
    predictionError: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictiveCommitment extends BaseContract {
  connect(runner?: ContractRunner | null): PredictiveCommitment;
  waitForDeployment(): Promise<this>;

  interface: PredictiveCommitmentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PENALTY_RATE: TypedContractMethod<[], [bigint], "view">;

  PENALTY_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_1_REWARD: TypedContractMethod<[], [bigint], "view">;

  TIER_1_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_2_REWARD: TypedContractMethod<[], [bigint], "view">;

  TIER_2_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_3_REWARD: TypedContractMethod<[], [bigint], "view">;

  TIER_3_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  commitments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        rentalId: string;
        committer: string;
        predictedAmount: bigint;
        predictedDuration: bigint;
        predictedVolume: bigint;
        commitmentTime: bigint;
        stakeAmount: bigint;
        isVerified: boolean;
        isSettled: boolean;
      }
    ],
    "view"
  >;

  submitCommitment: TypedContractMethod<
    [rentalId: BytesLike, predictedUsageHash: BytesLike, zkProof: BytesLike],
    [string],
    "payable"
  >;

  verifyAndReward: TypedContractMethod<
    [
      commitmentId: BytesLike,
      actualDuration: BigNumberish,
      actualAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  zkVerifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PENALTY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_1_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_1_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_2_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_2_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_3_REWARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_3_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        rentalId: string;
        committer: string;
        predictedAmount: bigint;
        predictedDuration: bigint;
        predictedVolume: bigint;
        commitmentTime: bigint;
        stakeAmount: bigint;
        isVerified: boolean;
        isSettled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitCommitment"
  ): TypedContractMethod<
    [rentalId: BytesLike, predictedUsageHash: BytesLike, zkProof: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verifyAndReward"
  ): TypedContractMethod<
    [
      commitmentId: BytesLike,
      actualDuration: BigNumberish,
      actualAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zkVerifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CommitmentSubmitted"
  ): TypedContractEvent<
    CommitmentSubmittedEvent.InputTuple,
    CommitmentSubmittedEvent.OutputTuple,
    CommitmentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "CommitmentVerified"
  ): TypedContractEvent<
    CommitmentVerifiedEvent.InputTuple,
    CommitmentVerifiedEvent.OutputTuple,
    CommitmentVerifiedEvent.OutputObject
  >;

  filters: {
    "CommitmentSubmitted(bytes32,bytes32,address,uint256)": TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;
    CommitmentSubmitted: TypedContractEvent<
      CommitmentSubmittedEvent.InputTuple,
      CommitmentSubmittedEvent.OutputTuple,
      CommitmentSubmittedEvent.OutputObject
    >;

    "CommitmentVerified(bytes32,uint256,uint256)": TypedContractEvent<
      CommitmentVerifiedEvent.InputTuple,
      CommitmentVerifiedEvent.OutputTuple,
      CommitmentVerifiedEvent.OutputObject
    >;
    CommitmentVerified: TypedContractEvent<
      CommitmentVerifiedEvent.InputTuple,
      CommitmentVerifiedEvent.OutputTuple,
      CommitmentVerifiedEvent.OutputObject
    >;
  };
}
