/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV4Router,
  IV4RouterInterface,
} from "../../../../contracts/src/UnifiedFlashLPV4.sol/IV4Router";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "currency0",
            type: "address",
          },
          {
            internalType: "address",
            name: "currency1",
            type: "address",
          },
          {
            internalType: "uint24",
            name: "fee",
            type: "uint24",
          },
          {
            internalType: "int24",
            name: "tickSpacing",
            type: "int24",
          },
          {
            internalType: "address",
            name: "hooks",
            type: "address",
          },
        ],
        internalType: "struct IV4Router.PoolKey",
        name: "key",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "int24",
            name: "tickLower",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "tickUpper",
            type: "int24",
          },
          {
            internalType: "int256",
            name: "liquidityDelta",
            type: "int256",
          },
          {
            internalType: "bytes32",
            name: "salt",
            type: "bytes32",
          },
        ],
        internalType: "struct IV4Router.ModifyLiquidityParams",
        name: "params",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "hookData",
        type: "bytes",
      },
    ],
    name: "addLiquidity",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IV4Router__factory {
  static readonly abi = _abi;
  static createInterface(): IV4RouterInterface {
    return new Interface(_abi) as IV4RouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IV4Router {
    return new Contract(address, _abi, runner) as unknown as IV4Router;
  }
}
