/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IRentalVault {
  export type PositionStruct = {
    owner: AddressLike;
    nftContract: AddressLike;
    tokenId: BigNumberish;
    pricePerSecond: BigNumberish;
    isListed: boolean;
    isLocked: boolean;
    minRentalDuration: BigNumberish;
    maxRentalDuration: BigNumberish;
  };

  export type PositionStructOutput = [
    owner: string,
    nftContract: string,
    tokenId: bigint,
    pricePerSecond: bigint,
    isListed: boolean,
    isLocked: boolean,
    minRentalDuration: bigint,
    maxRentalDuration: bigint
  ] & {
    owner: string;
    nftContract: string;
    tokenId: bigint;
    pricePerSecond: bigint;
    isListed: boolean;
    isLocked: boolean;
    minRentalDuration: bigint;
    maxRentalDuration: bigint;
  };
}

export interface IRentalVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositPosition"
      | "getPosition"
      | "listPosition"
      | "lockPosition"
      | "unlockPosition"
      | "withdrawPosition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PositionDeposited"
      | "PositionListed"
      | "PositionLocked"
      | "PositionUnlocked"
      | "PositionWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositPosition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPosition",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPosition",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPosition",
    data: BytesLike
  ): Result;
}

export namespace PositionDepositedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    owner: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    owner: string,
    nftContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    positionId: string;
    owner: string;
    nftContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionListedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    pricePerSecond: BigNumberish,
    minDuration: BigNumberish,
    maxDuration: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    pricePerSecond: bigint,
    minDuration: bigint,
    maxDuration: bigint
  ];
  export interface OutputObject {
    positionId: string;
    pricePerSecond: bigint;
    minDuration: bigint;
    maxDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLockedEvent {
  export type InputTuple = [positionId: BytesLike];
  export type OutputTuple = [positionId: string];
  export interface OutputObject {
    positionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionUnlockedEvent {
  export type InputTuple = [positionId: BytesLike];
  export type OutputTuple = [positionId: string];
  export interface OutputObject {
    positionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionWithdrawnEvent {
  export type InputTuple = [positionId: BytesLike, owner: AddressLike];
  export type OutputTuple = [positionId: string, owner: string];
  export interface OutputObject {
    positionId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRentalVault extends BaseContract {
  connect(runner?: ContractRunner | null): IRentalVault;
  waitForDeployment(): Promise<this>;

  interface: IRentalVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositPosition: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;

  getPosition: TypedContractMethod<
    [positionId: BytesLike],
    [IRentalVault.PositionStructOutput],
    "view"
  >;

  listPosition: TypedContractMethod<
    [
      positionId: BytesLike,
      pricePerSecond: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lockPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  unlockPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositPosition"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BytesLike],
    [IRentalVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listPosition"
  ): TypedContractMethod<
    [
      positionId: BytesLike,
      pricePerSecond: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "PositionDeposited"
  ): TypedContractEvent<
    PositionDepositedEvent.InputTuple,
    PositionDepositedEvent.OutputTuple,
    PositionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PositionListed"
  ): TypedContractEvent<
    PositionListedEvent.InputTuple,
    PositionListedEvent.OutputTuple,
    PositionListedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLocked"
  ): TypedContractEvent<
    PositionLockedEvent.InputTuple,
    PositionLockedEvent.OutputTuple,
    PositionLockedEvent.OutputObject
  >;
  getEvent(
    key: "PositionUnlocked"
  ): TypedContractEvent<
    PositionUnlockedEvent.InputTuple,
    PositionUnlockedEvent.OutputTuple,
    PositionUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "PositionWithdrawn"
  ): TypedContractEvent<
    PositionWithdrawnEvent.InputTuple,
    PositionWithdrawnEvent.OutputTuple,
    PositionWithdrawnEvent.OutputObject
  >;

  filters: {
    "PositionDeposited(bytes32,address,address,uint256)": TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;
    PositionDeposited: TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;

    "PositionListed(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PositionListedEvent.InputTuple,
      PositionListedEvent.OutputTuple,
      PositionListedEvent.OutputObject
    >;
    PositionListed: TypedContractEvent<
      PositionListedEvent.InputTuple,
      PositionListedEvent.OutputTuple,
      PositionListedEvent.OutputObject
    >;

    "PositionLocked(bytes32)": TypedContractEvent<
      PositionLockedEvent.InputTuple,
      PositionLockedEvent.OutputTuple,
      PositionLockedEvent.OutputObject
    >;
    PositionLocked: TypedContractEvent<
      PositionLockedEvent.InputTuple,
      PositionLockedEvent.OutputTuple,
      PositionLockedEvent.OutputObject
    >;

    "PositionUnlocked(bytes32)": TypedContractEvent<
      PositionUnlockedEvent.InputTuple,
      PositionUnlockedEvent.OutputTuple,
      PositionUnlockedEvent.OutputObject
    >;
    PositionUnlocked: TypedContractEvent<
      PositionUnlockedEvent.InputTuple,
      PositionUnlockedEvent.OutputTuple,
      PositionUnlockedEvent.OutputObject
    >;

    "PositionWithdrawn(bytes32,address)": TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;
    PositionWithdrawn: TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;
  };
}
