/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IYellowChannelManager {
  export type ChannelStruct = {
    participant1: AddressLike;
    participant2: AddressLike;
    balance1: BigNumberish;
    balance2: BigNumberish;
    totalDeposit: BigNumberish;
    nonce: BigNumberish;
    timeout: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
    isDisputed: boolean;
  };

  export type ChannelStructOutput = [
    participant1: string,
    participant2: string,
    balance1: bigint,
    balance2: bigint,
    totalDeposit: bigint,
    nonce: bigint,
    timeout: bigint,
    expiresAt: bigint,
    isActive: boolean,
    isDisputed: boolean
  ] & {
    participant1: string;
    participant2: string;
    balance1: bigint;
    balance2: bigint;
    totalDeposit: bigint;
    nonce: bigint;
    timeout: bigint;
    expiresAt: bigint;
    isActive: boolean;
    isDisputed: boolean;
  };
}

export interface IYellowChannelManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeChannel"
      | "getChannel"
      | "hasActiveChannel"
      | "openChannel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ChannelClosed" | "ChannelOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeChannel",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveChannel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openChannel",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openChannel",
    data: BytesLike
  ): Result;
}

export namespace ChannelClosedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    finalBalance1: BigNumberish,
    finalBalance2: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    finalBalance1: bigint,
    finalBalance2: bigint
  ];
  export interface OutputObject {
    channelId: string;
    finalBalance1: bigint;
    finalBalance2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelOpenedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    participant1: AddressLike,
    participant2: AddressLike,
    deposit: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    participant1: string,
    participant2: string,
    deposit: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    channelId: string;
    participant1: string;
    participant2: string;
    deposit: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IYellowChannelManager extends BaseContract {
  connect(runner?: ContractRunner | null): IYellowChannelManager;
  waitForDeployment(): Promise<this>;

  interface: IYellowChannelManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeChannel: TypedContractMethod<
    [
      channelId: BytesLike,
      finalBalance1: BigNumberish,
      finalBalance2: BigNumberish,
      nonce: BigNumberish,
      signature1: BytesLike,
      signature2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getChannel: TypedContractMethod<
    [channelId: BytesLike],
    [IYellowChannelManager.ChannelStructOutput],
    "view"
  >;

  hasActiveChannel: TypedContractMethod<
    [participant: AddressLike],
    [boolean],
    "view"
  >;

  openChannel: TypedContractMethod<
    [participant2: AddressLike, duration: BigNumberish],
    [string],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeChannel"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      finalBalance1: BigNumberish,
      finalBalance2: BigNumberish,
      nonce: BigNumberish,
      signature1: BytesLike,
      signature2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChannel"
  ): TypedContractMethod<
    [channelId: BytesLike],
    [IYellowChannelManager.ChannelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasActiveChannel"
  ): TypedContractMethod<[participant: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "openChannel"
  ): TypedContractMethod<
    [participant2: AddressLike, duration: BigNumberish],
    [string],
    "payable"
  >;

  getEvent(
    key: "ChannelClosed"
  ): TypedContractEvent<
    ChannelClosedEvent.InputTuple,
    ChannelClosedEvent.OutputTuple,
    ChannelClosedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelOpened"
  ): TypedContractEvent<
    ChannelOpenedEvent.InputTuple,
    ChannelOpenedEvent.OutputTuple,
    ChannelOpenedEvent.OutputObject
  >;

  filters: {
    "ChannelClosed(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;
    ChannelClosed: TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;

    "ChannelOpened(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;
    ChannelOpened: TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;
  };
}
