/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RentalManager {
  export type RentalStateStruct = {
    originalOwner: AddressLike;
    currentRenter: AddressLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    pricePerSecond: BigNumberish;
    collateralAmount: BigNumberish;
    isActive: boolean;
    channelId: BytesLike;
    positionId: BytesLike;
  };

  export type RentalStateStructOutput = [
    originalOwner: string,
    currentRenter: string,
    startTime: bigint,
    endTime: bigint,
    pricePerSecond: bigint,
    collateralAmount: bigint,
    isActive: boolean,
    channelId: string,
    positionId: string
  ] & {
    originalOwner: string;
    currentRenter: string;
    startTime: bigint;
    endTime: bigint;
    pricePerSecond: bigint;
    collateralAmount: bigint;
    isActive: boolean;
    channelId: string;
    positionId: string;
  };
}

export interface RentalManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PLATFORM_FEE"
      | "MAX_RENTAL_DURATION"
      | "MIN_RENTAL_DURATION"
      | "calculateCurrentFees"
      | "createRental"
      | "emergencyClose"
      | "endRental"
      | "extendRental"
      | "getRental"
      | "getRenterRentals"
      | "minCollateralBps"
      | "owner"
      | "pause"
      | "paused"
      | "platformFeeBps"
      | "positionToRental"
      | "renounceOwnership"
      | "rentalVault"
      | "rentals"
      | "setMinCollateral"
      | "setPlatformFee"
      | "totalFeesCollected"
      | "totalRentals"
      | "transferOwnership"
      | "unpause"
      | "yellowChannelManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralRequirementUpdated"
      | "EmergencyClose"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeeUpdated"
      | "RentalCreated"
      | "RentalEnded"
      | "RentalExtended"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RENTAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_RENTAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCurrentFees",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createRental",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyClose",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endRental",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extendRental",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRental",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRenterRentals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minCollateralBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positionToRental",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rentalVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rentals", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setMinCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRentals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "yellowChannelManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RENTAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_RENTAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCurrentFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRental",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyClose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endRental", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "extendRental",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRental", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRenterRentals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minCollateralBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionToRental",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rentalVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRentals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "yellowChannelManager",
    data: BytesLike
  ): Result;
}

export namespace CollateralRequirementUpdatedEvent {
  export type InputTuple = [newBps: BigNumberish];
  export type OutputTuple = [newBps: bigint];
  export interface OutputObject {
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyCloseEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    closer: AddressLike,
    penalty: BigNumberish
  ];
  export type OutputTuple = [rentalId: string, closer: string, penalty: bigint];
  export interface OutputObject {
    rentalId: string;
    closer: string;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentalCreatedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    positionId: BytesLike,
    renter: AddressLike,
    owner: AddressLike,
    duration: BigNumberish,
    pricePerSecond: BigNumberish,
    collateral: BigNumberish
  ];
  export type OutputTuple = [
    rentalId: string,
    positionId: string,
    renter: string,
    owner: string,
    duration: bigint,
    pricePerSecond: bigint,
    collateral: bigint
  ];
  export interface OutputObject {
    rentalId: string;
    positionId: string;
    renter: string;
    owner: string;
    duration: bigint;
    pricePerSecond: bigint;
    collateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentalEndedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    totalFee: BigNumberish,
    actualDuration: BigNumberish,
    refund: BigNumberish
  ];
  export type OutputTuple = [
    rentalId: string,
    totalFee: bigint,
    actualDuration: bigint,
    refund: bigint
  ];
  export interface OutputObject {
    rentalId: string;
    totalFee: bigint;
    actualDuration: bigint;
    refund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentalExtendedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    newEndTime: BigNumberish,
    additionalCollateral: BigNumberish
  ];
  export type OutputTuple = [
    rentalId: string,
    newEndTime: bigint,
    additionalCollateral: bigint
  ];
  export interface OutputObject {
    rentalId: string;
    newEndTime: bigint;
    additionalCollateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RentalManager extends BaseContract {
  connect(runner?: ContractRunner | null): RentalManager;
  waitForDeployment(): Promise<this>;

  interface: RentalManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_RENTAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_RENTAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  calculateCurrentFees: TypedContractMethod<
    [rentalId: BytesLike],
    [bigint],
    "view"
  >;

  createRental: TypedContractMethod<
    [
      positionId: BytesLike,
      owner: AddressLike,
      duration: BigNumberish,
      pricePerSecond: BigNumberish,
      channelId: BytesLike
    ],
    [string],
    "payable"
  >;

  emergencyClose: TypedContractMethod<
    [rentalId: BytesLike],
    [void],
    "nonpayable"
  >;

  endRental: TypedContractMethod<[rentalId: BytesLike], [void], "nonpayable">;

  extendRental: TypedContractMethod<
    [rentalId: BytesLike, additionalDuration: BigNumberish],
    [void],
    "payable"
  >;

  getRental: TypedContractMethod<
    [rentalId: BytesLike],
    [RentalManager.RentalStateStructOutput],
    "view"
  >;

  getRenterRentals: TypedContractMethod<
    [renter: AddressLike],
    [string[]],
    "view"
  >;

  minCollateralBps: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  positionToRental: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rentalVault: TypedContractMethod<[], [string], "view">;

  rentals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        originalOwner: string;
        currentRenter: string;
        startTime: bigint;
        endTime: bigint;
        pricePerSecond: bigint;
        collateralAmount: bigint;
        isActive: boolean;
        channelId: string;
        positionId: string;
      }
    ],
    "view"
  >;

  setMinCollateral: TypedContractMethod<
    [newBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  totalRentals: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  yellowChannelManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RENTAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_RENTAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateCurrentFees"
  ): TypedContractMethod<[rentalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createRental"
  ): TypedContractMethod<
    [
      positionId: BytesLike,
      owner: AddressLike,
      duration: BigNumberish,
      pricePerSecond: BigNumberish,
      channelId: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "emergencyClose"
  ): TypedContractMethod<[rentalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "endRental"
  ): TypedContractMethod<[rentalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "extendRental"
  ): TypedContractMethod<
    [rentalId: BytesLike, additionalDuration: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getRental"
  ): TypedContractMethod<
    [rentalId: BytesLike],
    [RentalManager.RentalStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRenterRentals"
  ): TypedContractMethod<[renter: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "minCollateralBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "positionToRental"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rentalVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rentals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string
      ] & {
        originalOwner: string;
        currentRenter: string;
        startTime: bigint;
        endTime: bigint;
        pricePerSecond: bigint;
        collateralAmount: bigint;
        isActive: boolean;
        channelId: string;
        positionId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMinCollateral"
  ): TypedContractMethod<[newBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRentals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yellowChannelManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CollateralRequirementUpdated"
  ): TypedContractEvent<
    CollateralRequirementUpdatedEvent.InputTuple,
    CollateralRequirementUpdatedEvent.OutputTuple,
    CollateralRequirementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyClose"
  ): TypedContractEvent<
    EmergencyCloseEvent.InputTuple,
    EmergencyCloseEvent.OutputTuple,
    EmergencyCloseEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RentalCreated"
  ): TypedContractEvent<
    RentalCreatedEvent.InputTuple,
    RentalCreatedEvent.OutputTuple,
    RentalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RentalEnded"
  ): TypedContractEvent<
    RentalEndedEvent.InputTuple,
    RentalEndedEvent.OutputTuple,
    RentalEndedEvent.OutputObject
  >;
  getEvent(
    key: "RentalExtended"
  ): TypedContractEvent<
    RentalExtendedEvent.InputTuple,
    RentalExtendedEvent.OutputTuple,
    RentalExtendedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CollateralRequirementUpdated(uint256)": TypedContractEvent<
      CollateralRequirementUpdatedEvent.InputTuple,
      CollateralRequirementUpdatedEvent.OutputTuple,
      CollateralRequirementUpdatedEvent.OutputObject
    >;
    CollateralRequirementUpdated: TypedContractEvent<
      CollateralRequirementUpdatedEvent.InputTuple,
      CollateralRequirementUpdatedEvent.OutputTuple,
      CollateralRequirementUpdatedEvent.OutputObject
    >;

    "EmergencyClose(bytes32,address,uint256)": TypedContractEvent<
      EmergencyCloseEvent.InputTuple,
      EmergencyCloseEvent.OutputTuple,
      EmergencyCloseEvent.OutputObject
    >;
    EmergencyClose: TypedContractEvent<
      EmergencyCloseEvent.InputTuple,
      EmergencyCloseEvent.OutputTuple,
      EmergencyCloseEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "RentalCreated(bytes32,bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      RentalCreatedEvent.InputTuple,
      RentalCreatedEvent.OutputTuple,
      RentalCreatedEvent.OutputObject
    >;
    RentalCreated: TypedContractEvent<
      RentalCreatedEvent.InputTuple,
      RentalCreatedEvent.OutputTuple,
      RentalCreatedEvent.OutputObject
    >;

    "RentalEnded(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;
    RentalEnded: TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;

    "RentalExtended(bytes32,uint256,uint256)": TypedContractEvent<
      RentalExtendedEvent.InputTuple,
      RentalExtendedEvent.OutputTuple,
      RentalExtendedEvent.OutputObject
    >;
    RentalExtended: TypedContractEvent<
      RentalExtendedEvent.InputTuple,
      RentalExtendedEvent.OutputTuple,
      RentalExtendedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
