/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RentalVault {
  export type PositionStruct = {
    owner: AddressLike;
    nftContract: AddressLike;
    tokenId: BigNumberish;
    pricePerSecond: BigNumberish;
    isListed: boolean;
    isLocked: boolean;
    minRentalDuration: BigNumberish;
    maxRentalDuration: BigNumberish;
  };

  export type PositionStructOutput = [
    owner: string,
    nftContract: string,
    tokenId: bigint,
    pricePerSecond: bigint,
    isListed: boolean,
    isLocked: boolean,
    minRentalDuration: bigint,
    maxRentalDuration: bigint
  ] & {
    owner: string;
    nftContract: string;
    tokenId: bigint;
    pricePerSecond: bigint;
    isListed: boolean;
    isLocked: boolean;
    minRentalDuration: bigint;
    maxRentalDuration: bigint;
  };
}

export interface RentalVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositPosition"
      | "getOwnerPositions"
      | "getPosition"
      | "listPosition"
      | "lockPosition"
      | "onERC721Received"
      | "owner"
      | "pause"
      | "paused"
      | "positions"
      | "renounceOwnership"
      | "totalPositions"
      | "transferOwnership"
      | "unlistPosition"
      | "unlockPosition"
      | "unpause"
      | "withdrawPosition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "PositionDeposited"
      | "PositionListed"
      | "PositionLocked"
      | "PositionUnlisted"
      | "PositionUnlocked"
      | "PositionWithdrawn"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositPosition",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPosition",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPositions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlistPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockPosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawPosition",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlistPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPosition",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionDepositedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    owner: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    owner: string,
    nftContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    positionId: string;
    owner: string;
    nftContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionListedEvent {
  export type InputTuple = [
    positionId: BytesLike,
    pricePerSecond: BigNumberish,
    minDuration: BigNumberish,
    maxDuration: BigNumberish
  ];
  export type OutputTuple = [
    positionId: string,
    pricePerSecond: bigint,
    minDuration: bigint,
    maxDuration: bigint
  ];
  export interface OutputObject {
    positionId: string;
    pricePerSecond: bigint;
    minDuration: bigint;
    maxDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionLockedEvent {
  export type InputTuple = [positionId: BytesLike];
  export type OutputTuple = [positionId: string];
  export interface OutputObject {
    positionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionUnlistedEvent {
  export type InputTuple = [positionId: BytesLike];
  export type OutputTuple = [positionId: string];
  export interface OutputObject {
    positionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionUnlockedEvent {
  export type InputTuple = [positionId: BytesLike];
  export type OutputTuple = [positionId: string];
  export interface OutputObject {
    positionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionWithdrawnEvent {
  export type InputTuple = [positionId: BytesLike, owner: AddressLike];
  export type OutputTuple = [positionId: string, owner: string];
  export interface OutputObject {
    positionId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RentalVault extends BaseContract {
  connect(runner?: ContractRunner | null): RentalVault;
  waitForDeployment(): Promise<this>;

  interface: RentalVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositPosition: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;

  getOwnerPositions: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getPosition: TypedContractMethod<
    [positionId: BytesLike],
    [RentalVault.PositionStructOutput],
    "view"
  >;

  listPosition: TypedContractMethod<
    [
      positionId: BytesLike,
      pricePerSecond: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lockPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  positions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, bigint] & {
        owner: string;
        nftContract: string;
        tokenId: bigint;
        pricePerSecond: bigint;
        isListed: boolean;
        isLocked: boolean;
        minRentalDuration: bigint;
        maxRentalDuration: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalPositions: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlistPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  unlockPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawPosition: TypedContractMethod<
    [positionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositPosition"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOwnerPositions"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BytesLike],
    [RentalVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listPosition"
  ): TypedContractMethod<
    [
      positionId: BytesLike,
      pricePerSecond: BigNumberish,
      minDuration: BigNumberish,
      maxDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean, bigint, bigint] & {
        owner: string;
        nftContract: string;
        tokenId: bigint;
        pricePerSecond: bigint;
        isListed: boolean;
        isLocked: boolean;
        minRentalDuration: bigint;
        maxRentalDuration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPositions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlistPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPosition"
  ): TypedContractMethod<[positionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PositionDeposited"
  ): TypedContractEvent<
    PositionDepositedEvent.InputTuple,
    PositionDepositedEvent.OutputTuple,
    PositionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PositionListed"
  ): TypedContractEvent<
    PositionListedEvent.InputTuple,
    PositionListedEvent.OutputTuple,
    PositionListedEvent.OutputObject
  >;
  getEvent(
    key: "PositionLocked"
  ): TypedContractEvent<
    PositionLockedEvent.InputTuple,
    PositionLockedEvent.OutputTuple,
    PositionLockedEvent.OutputObject
  >;
  getEvent(
    key: "PositionUnlisted"
  ): TypedContractEvent<
    PositionUnlistedEvent.InputTuple,
    PositionUnlistedEvent.OutputTuple,
    PositionUnlistedEvent.OutputObject
  >;
  getEvent(
    key: "PositionUnlocked"
  ): TypedContractEvent<
    PositionUnlockedEvent.InputTuple,
    PositionUnlockedEvent.OutputTuple,
    PositionUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "PositionWithdrawn"
  ): TypedContractEvent<
    PositionWithdrawnEvent.InputTuple,
    PositionWithdrawnEvent.OutputTuple,
    PositionWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PositionDeposited(bytes32,address,address,uint256)": TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;
    PositionDeposited: TypedContractEvent<
      PositionDepositedEvent.InputTuple,
      PositionDepositedEvent.OutputTuple,
      PositionDepositedEvent.OutputObject
    >;

    "PositionListed(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PositionListedEvent.InputTuple,
      PositionListedEvent.OutputTuple,
      PositionListedEvent.OutputObject
    >;
    PositionListed: TypedContractEvent<
      PositionListedEvent.InputTuple,
      PositionListedEvent.OutputTuple,
      PositionListedEvent.OutputObject
    >;

    "PositionLocked(bytes32)": TypedContractEvent<
      PositionLockedEvent.InputTuple,
      PositionLockedEvent.OutputTuple,
      PositionLockedEvent.OutputObject
    >;
    PositionLocked: TypedContractEvent<
      PositionLockedEvent.InputTuple,
      PositionLockedEvent.OutputTuple,
      PositionLockedEvent.OutputObject
    >;

    "PositionUnlisted(bytes32)": TypedContractEvent<
      PositionUnlistedEvent.InputTuple,
      PositionUnlistedEvent.OutputTuple,
      PositionUnlistedEvent.OutputObject
    >;
    PositionUnlisted: TypedContractEvent<
      PositionUnlistedEvent.InputTuple,
      PositionUnlistedEvent.OutputTuple,
      PositionUnlistedEvent.OutputObject
    >;

    "PositionUnlocked(bytes32)": TypedContractEvent<
      PositionUnlockedEvent.InputTuple,
      PositionUnlockedEvent.OutputTuple,
      PositionUnlockedEvent.OutputObject
    >;
    PositionUnlocked: TypedContractEvent<
      PositionUnlockedEvent.InputTuple,
      PositionUnlockedEvent.OutputTuple,
      PositionUnlockedEvent.OutputObject
    >;

    "PositionWithdrawn(bytes32,address)": TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;
    PositionWithdrawn: TypedContractEvent<
      PositionWithdrawnEvent.InputTuple,
      PositionWithdrawnEvent.OutputTuple,
      PositionWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
