/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ITLVMCore {
  export type PredictiveCommitmentDataStruct = {
    hasCommitment: boolean;
    predictedUsage: BytesLike;
    zkProof: BytesLike;
  };

  export type PredictiveCommitmentDataStructOutput = [
    hasCommitment: boolean,
    predictedUsage: string,
    zkProof: string
  ] & { hasCommitment: boolean; predictedUsage: string; zkProof: string };
}

export interface TLVMCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COLLATERAL_MULTIPLIER"
      | "DECAY_RATE"
      | "MAX_RENTAL_DURATION"
      | "MIN_RENTAL_DURATION"
      | "PREDICTION_STAKE"
      | "createRental"
      | "endRental"
      | "listPosition"
      | "lpPositions"
      | "predictiveCommitment"
      | "rentals"
      | "temporalAMM"
      | "userRentals"
      | "virtualLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RentalCreated"
      | "RentalEnded"
      | "VirtualLiquidityActivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COLLATERAL_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DECAY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RENTAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_RENTAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PREDICTION_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRental",
    values: [
      BigNumberish,
      BigNumberish,
      ITLVMCore.PredictiveCommitmentDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "endRental",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listPosition",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lpPositions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictiveCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rentals", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "temporalAMM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userRentals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "virtualLiquidity",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COLLATERAL_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DECAY_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RENTAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_RENTAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PREDICTION_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRental",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endRental", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictiveCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rentals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "temporalAMM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRentals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "virtualLiquidity",
    data: BytesLike
  ): Result;
}

export namespace RentalCreatedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    renter: AddressLike,
    positionId: BigNumberish,
    duration: BigNumberish,
    temporalPrice: BigNumberish,
    hasCommitment: boolean
  ];
  export type OutputTuple = [
    rentalId: string,
    renter: string,
    positionId: bigint,
    duration: bigint,
    temporalPrice: bigint,
    hasCommitment: boolean
  ];
  export interface OutputObject {
    rentalId: string;
    renter: string;
    positionId: bigint;
    duration: bigint;
    temporalPrice: bigint;
    hasCommitment: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentalEndedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    actualDuration: BigNumberish,
    totalFee: BigNumberish,
    predictionReward: BigNumberish
  ];
  export type OutputTuple = [
    rentalId: string,
    actualDuration: bigint,
    totalFee: bigint,
    predictionReward: bigint
  ];
  export interface OutputObject {
    rentalId: string;
    actualDuration: bigint;
    totalFee: bigint;
    predictionReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VirtualLiquidityActivatedEvent {
  export type InputTuple = [
    rentalId: BytesLike,
    virtualAmount: BigNumberish,
    latencyBound: BigNumberish
  ];
  export type OutputTuple = [
    rentalId: string,
    virtualAmount: bigint,
    latencyBound: bigint
  ];
  export interface OutputObject {
    rentalId: string;
    virtualAmount: bigint;
    latencyBound: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TLVMCore extends BaseContract {
  connect(runner?: ContractRunner | null): TLVMCore;
  waitForDeployment(): Promise<this>;

  interface: TLVMCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COLLATERAL_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  DECAY_RATE: TypedContractMethod<[], [bigint], "view">;

  MAX_RENTAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_RENTAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  PREDICTION_STAKE: TypedContractMethod<[], [bigint], "view">;

  createRental: TypedContractMethod<
    [
      positionId: BigNumberish,
      duration: BigNumberish,
      commitment: ITLVMCore.PredictiveCommitmentDataStruct
    ],
    [string],
    "payable"
  >;

  endRental: TypedContractMethod<[rentalId: BytesLike], [void], "nonpayable">;

  listPosition: TypedContractMethod<
    [
      positionId: BigNumberish,
      basePrice: BigNumberish,
      minRental: BigNumberish,
      maxRental: BigNumberish,
      liquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lpPositions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        owner: string;
        token0: string;
        token1: string;
        liquidity: bigint;
        basePrice: bigint;
        minRental: bigint;
        maxRental: bigint;
        chainId: bigint;
        isListed: boolean;
        isRented: boolean;
      }
    ],
    "view"
  >;

  predictiveCommitment: TypedContractMethod<[], [string], "view">;

  rentals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        boolean,
        boolean
      ] & {
        id: string;
        renter: string;
        lpOwner: string;
        positionId: bigint;
        startTime: bigint;
        endTime: bigint;
        duration: bigint;
        liquidityAmount: bigint;
        basePricePerSecond: bigint;
        collateralAmount: bigint;
        hasCommitment: boolean;
        commitmentId: string;
        isActive: boolean;
        isVirtual: boolean;
      }
    ],
    "view"
  >;

  temporalAMM: TypedContractMethod<[], [string], "view">;

  userRentals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  virtualLiquidity: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COLLATERAL_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DECAY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RENTAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_RENTAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREDICTION_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createRental"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      duration: BigNumberish,
      commitment: ITLVMCore.PredictiveCommitmentDataStruct
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "endRental"
  ): TypedContractMethod<[rentalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listPosition"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      basePrice: BigNumberish,
      minRental: BigNumberish,
      maxRental: BigNumberish,
      liquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lpPositions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        owner: string;
        token0: string;
        token1: string;
        liquidity: bigint;
        basePrice: bigint;
        minRental: bigint;
        maxRental: bigint;
        chainId: bigint;
        isListed: boolean;
        isRented: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "predictiveCommitment"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rentals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        boolean,
        boolean
      ] & {
        id: string;
        renter: string;
        lpOwner: string;
        positionId: bigint;
        startTime: bigint;
        endTime: bigint;
        duration: bigint;
        liquidityAmount: bigint;
        basePricePerSecond: bigint;
        collateralAmount: bigint;
        hasCommitment: boolean;
        commitmentId: string;
        isActive: boolean;
        isVirtual: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "temporalAMM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userRentals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "virtualLiquidity"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "RentalCreated"
  ): TypedContractEvent<
    RentalCreatedEvent.InputTuple,
    RentalCreatedEvent.OutputTuple,
    RentalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RentalEnded"
  ): TypedContractEvent<
    RentalEndedEvent.InputTuple,
    RentalEndedEvent.OutputTuple,
    RentalEndedEvent.OutputObject
  >;
  getEvent(
    key: "VirtualLiquidityActivated"
  ): TypedContractEvent<
    VirtualLiquidityActivatedEvent.InputTuple,
    VirtualLiquidityActivatedEvent.OutputTuple,
    VirtualLiquidityActivatedEvent.OutputObject
  >;

  filters: {
    "RentalCreated(bytes32,address,uint256,uint256,uint256,bool)": TypedContractEvent<
      RentalCreatedEvent.InputTuple,
      RentalCreatedEvent.OutputTuple,
      RentalCreatedEvent.OutputObject
    >;
    RentalCreated: TypedContractEvent<
      RentalCreatedEvent.InputTuple,
      RentalCreatedEvent.OutputTuple,
      RentalCreatedEvent.OutputObject
    >;

    "RentalEnded(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;
    RentalEnded: TypedContractEvent<
      RentalEndedEvent.InputTuple,
      RentalEndedEvent.OutputTuple,
      RentalEndedEvent.OutputObject
    >;

    "VirtualLiquidityActivated(bytes32,uint256,uint256)": TypedContractEvent<
      VirtualLiquidityActivatedEvent.InputTuple,
      VirtualLiquidityActivatedEvent.OutputTuple,
      VirtualLiquidityActivatedEvent.OutputObject
    >;
    VirtualLiquidityActivated: TypedContractEvent<
      VirtualLiquidityActivatedEvent.InputTuple,
      VirtualLiquidityActivatedEvent.OutputTuple,
      VirtualLiquidityActivatedEvent.OutputObject
    >;
  };
}
