/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export type ModifyLiquidityParamsStruct = {
  tickLower: BigNumberish;
  tickUpper: BigNumberish;
  liquidityDelta: BigNumberish;
  salt: BytesLike;
};

export type ModifyLiquidityParamsStructOutput = [
  tickLower: bigint,
  tickUpper: bigint,
  liquidityDelta: bigint,
  salt: string
] & {
  tickLower: bigint;
  tickUpper: bigint;
  liquidityDelta: bigint;
  salt: string;
};

export type SwapParamsStruct = {
  zeroForOne: boolean;
  amountSpecified: BigNumberish;
  sqrtPriceLimitX96: BigNumberish;
};

export type SwapParamsStructOutput = [
  zeroForOne: boolean,
  amountSpecified: bigint,
  sqrtPriceLimitX96: bigint
] & { zeroForOne: boolean; amountSpecified: bigint; sqrtPriceLimitX96: bigint };

export interface V4TestRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "manager"
      | "redeem"
      | "swap"
      | "unlockCallback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [PoolKeyStruct, ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [PoolKeyStruct, SwapParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCallback",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockCallback",
    data: BytesLike
  ): Result;
}

export interface V4TestRouter extends BaseContract {
  connect(runner?: ContractRunner | null): V4TestRouter;
  waitForDeployment(): Promise<this>;

  interface: V4TestRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [void],
    "payable"
  >;

  manager: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<
    [currency: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swap: TypedContractMethod<
    [key: PoolKeyStruct, params: SwapParamsStruct, hookData: BytesLike],
    [void],
    "payable"
  >;

  unlockCallback: TypedContractMethod<
    [data: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "manager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [currency: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [key: PoolKeyStruct, params: SwapParamsStruct, hookData: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "unlockCallback"
  ): TypedContractMethod<[data: BytesLike], [string], "nonpayable">;

  filters: {};
}
