/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYellowChannelManager,
  IYellowChannelManagerInterface,
} from "../../../../contracts/src/interfaces/IYellowChannelManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "finalBalance1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "finalBalance2",
        type: "uint256",
      },
    ],
    name: "ChannelClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "participant1",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "participant2",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deposit",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "ChannelOpened",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "finalBalance1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "finalBalance2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature1",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature2",
        type: "bytes",
      },
    ],
    name: "closeChannel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32",
      },
    ],
    name: "getChannel",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "participant1",
            type: "address",
          },
          {
            internalType: "address",
            name: "participant2",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "balance1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "balance2",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalDeposit",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timeout",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expiresAt",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDisputed",
            type: "bool",
          },
        ],
        internalType: "struct IYellowChannelManager.Channel",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "participant",
        type: "address",
      },
    ],
    name: "hasActiveChannel",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "participant2",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "openChannel",
    outputs: [
      {
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IYellowChannelManager__factory {
  static readonly abi = _abi;
  static createInterface(): IYellowChannelManagerInterface {
    return new Interface(_abi) as IYellowChannelManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYellowChannelManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IYellowChannelManager;
  }
}
